env: "local" #local, dev, prod
storage_path: "./storage/storage.db"
storage_image_path: "./images" #file system directory, not db
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
